apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  namespace: common-nginx
  labels:
    app: nginx
    env:  stage
data:
  data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to Custom Nginx Service!</title>
    <style>
    html { color-scheme: light dark; }
    body { width: 35em; margin: 0 auto;
    font-family: Tahoma, Verdana, Arial, sans-serif; }
    </style>
    </head>
    <body>
    <h1>Welcome to Custom Nginx Service!</h1>
    <p>If you see this page, the nginx 2 web server is successfully installed and
    working. Further configuration is required.</p>

    <p>For online documentation and support please refer to
    <a href="http://nginx.org/">nginx.org</a>.<br/>
    Commercial support is available at
    <a href="http://nginx.com/">nginx.com</a>.</p>

    <p><em>Thank you for using nginx.</em></p>
    </body>
    </html>

  default.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      #access_log  /var/log/nginx/host.access.log  main;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      location /ready {
        return 200;
        access_log  /var/log/nginx/health.log;
      }

      location /health {
        return 200 "Welcome to Custom Nginx Service";
        access_log  /var/log/nginx/health.log;
      }
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }