apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: common-nginx
  labels:
    app: nginx
    env: stage
spec:
  selector:
    app: nginx
    env: stage
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP